msg: dev
SCHEMA_REGISTRY_URL: http://localhost:8081
BOOTSTRAP_SERVERS_CONFIG: http://localhost:9092
AUTO_OFFSET_RESET_CONFIG: earliest
COMMIT_INTERVAL_MS_CONFIG: 100000
CLIENT_ID_CONFIG:
APPLICATION_ID_CONFIG:

